# Generated by Django 5.1.6 on 2025-02-13 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="brach",
            new_name="branch",
        ),
    ]
