# Generated by Django 5.1.5 on 2025-02-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=12)),
                ("position", models.CharField(max_length=100)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highest_degree", models.CharField(max_length=255)),
                ("university", models.CharField(max_length=255)),
                ("graduation_year", models.IntegerField()),
                ("specialization", models.CharField(max_length=255)),
                ("percentage", models.FloatField()),
                (
                    "education_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="education_proofs/"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="selection_form.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=255)),
                ("ifsc_code", models.CharField(max_length=20)),
                ("branch_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="selection_form.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreviousEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("employment_duration", models.CharField(max_length=255)),
                ("reason_for_leaving", models.CharField(max_length=255)),
                ("skills_acquired", models.TextField()),
                (
                    "company_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_employment",
                        to="selection_form.employee",
                    ),
                ),
            ],
        ),
    ]
