# Generated by Django 5.1.5 on 2025-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selection_form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_experienced",
            field=models.BooleanField(
                choices=[(True, "Experienced"), (False, "Fresher")], default=False
            ),
        ),
    ]
