# Generated by Django 5.1.5 on 2025-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selection_form", "0002_employee_is_experienced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="is_experienced",
        ),
        migrations.AddField(
            model_name="employee",
            name="experience",
            field=models.CharField(
                choices=[
                    ("fresher", "Fresher"),
                    ("1-3 years", "1-3 Years"),
                    ("3-5 years", "3-5 Years"),
                    ("5+ years", "5+ Years"),
                ],
                default="fresher",
                max_length=20,
            ),
        ),
    ]
