# Generated by Django 5.1.5 on 2025-02-10 10:42

import selection_form.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selection_form", "0003_remove_employee_is_experienced_employee_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="education_proof",
            field=models.FileField(
                blank=True, null=True, upload_to=selection_form.models.upload_path
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to=selection_form.models.upload_path
            ),
        ),
    ]
