# Generated by Django 5.1.5 on 2025-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="pics")),
                ("desc", models.CharField()),
                ("price", models.IntegerField()),
                ("offer", models.BooleanField(default=False)),
            ],
        ),
    ]
