# Generated by Django 5.1.5 on 2025-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="desc",
            field=models.TextField(),
        ),
    ]
