# Generated by Django 5.1.5 on 2025-01-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0002_alter_destination_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination_deatils",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="pics")),
                ("area_desc", models.TextField()),
                ("price", models.IntegerField()),
                ("offer", models.BooleanField(default=False)),
                (
                    "areas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="travels.destination",
                    ),
                ),
            ],
        ),
    ]
