# Generated by Django 5.1.5 on 2025-01-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0005_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="Comments",
            new_name="content",
        ),
        migrations.AddField(
            model_name="comments",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="travels.destination",
            ),
            preserve_default=False,
        ),
    ]
