# Generated by Django 5.1.5 on 2025-01-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0007_alter_comments_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="travels.comments",
            ),
        ),
    ]
