# Generated by Django 5.1.5 on 2025-01-29 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0008_comments_parent_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="destination_deatils",
            name="disliked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_destinations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="destination_deatils",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_destinations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
