# Generated by Django 5.1.6 on 2025-02-14 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="blogs",
            new_name="blog",
        ),
    ]
